name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: run a multi-line script
      run: mvn clean install
        echo Add other actions to build,
        echo test, and deploy your project.
